# # Build stage
# FROM golang:1.25 as builder

# WORKDIR /

# COPY . .

# # RUN go build -o 
# # Build static binary
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# # Runtime stage
# FROM debian:bullseye-slim

# WORKDIR /

# COPY --from=builder /main .

# EXPOSE 8080
# CMD ["./main"]

# Development Stage
FROM golang:1.25 as dev

# Install CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

# Copy go.mod and go.sum early for better layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Start CompileDaemon to auto-rebuild and rerun on changes
CMD ["CompileDaemon", "--build=go build -o main .", "--command=./main", "--exclude-dir=.git"]
